In [8]:
import pandas as pd
pd.set_option('display.max_rows', 200)  # or 1000
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data.csv', header='infer')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9,18,21,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [54]:
def is_graffiti(row):
  if pd.notnull(row.descriptor) and 'graffiti' in row.descriptor.lower():
    return True
  elif 'graffiti' in row.complaint_type.lower():
    return True
  else:
    return False

#why not just do this all on a sample and not the full dataset?
#you've never explicitly gone over the python 'in' operator so this was confusing
# and I spent awhile down the rabbit hole of pandas str.contains()

#sample = df.sample(10000)
#sample['graffiti_flag'] = sample.apply(is_graffiti, axis=1)
#sample.sort_values(by=['graffiti_flag','complaint_type'], ascending=False)
#sample_graffiti = sample[sample.graffiti_flag]
#sample_graffiti
df['graffiti_flag'] = df.apply(is_graffiti, axis=1)
df_graffiti = df[df.graffiti_flag == True] #I don't understand why the simpler version works?
df_graffiti.groupby('community_board').size()

community_board
0 Unspecified                 541
01 BRONX                      312
01 BROOKLYN                  1797
01 MANHATTAN                  146
01 QUEENS                     573
01 STATEN ISLAND              255
02 BRONX                      243
02 BROOKLYN                   315
02 MANHATTAN                  598
02 QUEENS                     219
02 STATEN ISLAND               42
03 BRONX                      320
03 BROOKLYN                  1252
03 MANHATTAN                 1593
03 QUEENS                     203
03 STATEN ISLAND               40
04 BRONX                      337
04 BROOKLYN                  1429
04 MANHATTAN                  307
04 QUEENS                     353
05 BRONX                      402
05 BROOKLYN                   962
05 MANHATTAN                  284
05 QUEENS                     219
06 BRONX                      446
06 BROOKLYN                   401
06 MANHATTAN                  165
06 QUEENS                      68
07 BRONX                      322
07 BROOKLYN                   779
07 MANHATTAN                  224
07 QUEENS                     350
08 BRONX                      127
08 BROOKLYN                   505
08 MANHATTAN                  273
08 QUEENS                     129
09 BRONX                      464
09 BROOKLYN                   403
09 MANHATTAN                  202
09 QUEENS                     470
10 BRONX                      150
10 BROOKLYN                   268
10 MANHATTAN                  266
10 QUEENS                     202
11 BRONX                      267
11 BROOKLYN                   474
11 MANHATTAN                  229
11 QUEENS                      57
12 BRONX                      426
12 BROOKLYN                   532
12 MANHATTAN                  459
12 QUEENS                     539
13 BROOKLYN                   196
13 QUEENS                     142
14 BROOKLYN                   532
14 QUEENS                      91
15 BROOKLYN                   329
16 BROOKLYN                   371
17 BROOKLYN                   480
18 BROOKLYN                   410
26 BRONX                        5
27 BRONX                        4
28 BRONX                        2
55 BROOKLYN                     2
64 MANHATTAN                    1
81 QUEENS                       5
Unspecified BRONX             615
Unspecified BROOKLYN          591
Unspecified MANHATTAN         405
Unspecified QUEENS            254
Unspecified STATEN ISLAND       8
dtype: int64

In [53]:
df_graffiti.groupby('community_board').size().nlargest(10) #why use nlargest and not sort?

community_board
01 BROOKLYN             1797
03 MANHATTAN            1593
04 BROOKLYN             1429
03 BROOKLYN             1252
05 BROOKLYN              962
07 BROOKLYN              779
Unspecified BRONX        615
02 MANHATTAN             598
Unspecified BROOKLYN     591
01 QUEENS                573
dtype: int64